export const GET_ERRORS = 'GET_ERRORS'; 
export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN = 'LOGIN';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_TO_CART_USER = 'ADD_TO_CART_USER';
export const GET_CART_ITEM_USER = 'GET_CART_ITEM_USER'
export const REMOVE_CART_ITEM_USER = 'REMOVE_CART_ITEM_USER';
export const INCREASE_QUANTITY_ITEM = 'INCREASE_QUANTITY_ITEM'
export const DESCREASE_QUANTITY_ITEM = 'DESCREASE_QUANTITY_ITEM'
 


// PRODUCT
export const GET_PRODUCT_BY_SELL = 'GET_PRODUCT_BY_SELL';
export const GET_PRODUCT_BY_ARRIVAL = 'GET_PRODUCT_BY_ARRIVAL';
export const REQUEST_GET = 'REQUEST_GET';

export const ADD_BRANDS = 'ADD_BRANDS';
export const ADD_WOODS = 'ADD_WOODS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_WOODS = 'GET_WOODS';
export const GET_PRODUCT_TO_SHOP = 'GET_PRODUCT_TO_SHOP';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_BRANDS_ERROR = 'ADD_BRANDS_ERROR';
export const ADD_WOODS_ERROR = 'ADD_WOODS_ERROR';
// PRODUCT DETAIL
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL';



// ERROR
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ERROR = 'ERROR';




// SNACKBAR
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

